set(CUTTER_DIR_NAME "RadareOrg/Cutter")
if(WIN32)
    set(CMAKE_INSTALL_BINDIR "." CACHE PATH "Executable install directory")
    set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE PATH "Include install directory")
    set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "Library install directory")
    set(CMAKE_INSTALL_DATAROOTDIR "./" CACHE PATH "Resource installation directory")
    set(CUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}" CACHE PATH "Resource installation directory")
elseif(APPLE)
    include(GNUInstallDirs) #TODO: use appropriate paths for macOS
    set(CUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/${CUTTER_DIR_NAME}" CACHE PATH "Resource installation directory")
else()
    include(GNUInstallDirs)
    set(CUTTER_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/${CUTTER_DIR_NAME}" CACHE PATH "Resource installation directory")
endif()
set(ConfigPackageLocation "${CMAKE_INSTALL_LIBDIR}/Cutter" CACHE PATH "Cmake file install location")
